### ISSUE TITLE
/api/extensionquery response is empty

### ISSUE THREAD

**Issue by sevetseh28** [coder/code-marketplace#106]
Hi, Im trying to deploy code-marketplace locally using this compose file:

```
version: '3.8'

services:
  code-marketplace:
    image: ghcr.io/coder/code-marketplace:v2.3.1
    container_name: code-marketplace
    command: server --extensions-dir /extensions --address 0.0.0.0:3001
    volumes:
      - ./extensions:/extensions
    expose:
      - "3001"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - code-marketplace
    restart: unless-stopped
```

I'm adding extensions successfully with the `add` command but when I hit `https://localhost/api/extensionquery` with a POST request I get this response:

```json
{
    "results": [
        {
            "extensions": [],
            "resultMetadata": [
                {
                    "metadataType": "ResultCount",
                    "metadataItems": [
                        {
                            "name": "TotalCount",
                            "count": 0
                        }
                    ]
                }
            ]
        }
    ]
}
```

I've tried restarting the server already. I can also see the extension folders correctly.
Any ideas?

Thanks
